### ISSUE TITLE
Bug Report - Spoofer.js

### ISSUE THREAD

**Issue by VillainsRule4000** [GooseterV/Blooket#22] opened 2022-06-15 00:23 UTC
When I try to run spoofer.js, it Pauses in Debugger and doesn't work.

"Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules"

It should have run a spoofer...

This is the most current version.

I am on a Mac, using Chrome.

**Comment by GooseterV** [comment] 2022-06-15 22:01
It should be fixed, there was an issue with a missing variable, but now it's solved.

**Comment by VillainsRule4000** [comment] 2022-06-15 22:12
It still isn't working for me?

**Comment by VillainsRule4000** [comment] 2022-06-16 17:33
@GooseterV It still does not work for me.

**Comment by GooseterV** [comment] 2022-06-16 19:09
Are you using the latest version? Have you updated your bookmarks if using them?

**Comment by GooseterV** [comment] 2022-06-16 19:10
I just tried it again and there's nothing wrong with it that I can see. I've tried the obfuscated version and the obfuscated version and they both work as intended.

**Comment by VillainsRule4000** [comment] 2022-06-16 21:11
@GooseterV Spoofer.js is for the game lobby or Blooks page?

**Comment by GooseterV** [comment] 2022-06-16 23:24
Blooks page, have you been using it in the lobby?

**Comment by VillainsRule4000** [comment] 2022-06-16 23:56
@GooseterV No, I've been using it on the Blooks page. The console now reads "Uncaught TypeError: Cannot read properties of undefined (reading 'firstElementChild')".

**Comment by GooseterV** [comment] 2022-06-17 01:57
are you using it on some sort of mobile device? some of the elements may be different if you're using it on a phone.

**Comment by VillainsRule4000** [comment] 2022-06-17 11:42
@GooseterV I am on a Mac, using the latest version of Chrome.

**Comment by VillainsRule4000** [comment] 2022-06-19 02:19
Additionally, the Extend Stats doesn't work.

**Comment by GooseterV** [comment] 2022-06-19 02:24
Extend stats has been discontinued since the beginning of june. Spoofer should still be working 100% fine and dandy. I used it on both my phone and computer and it works fine.

**Comment by GooseterV** [comment] 2022-06-28 19:28
Ok if anything else has happened, let me know. I have fixed all bugs on all of my scripts for now but please do report them if there's anything else.

**Closed by GooseterV** 2022-06-28 19:28 UTC
Labels: bug
